[package]
name = "pai"
version = "1.0.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
rust_tokenizers = "8.1.0"
regex = "1.9.5"